### ISSUE TITLE
Analyze the up-to-dateness of the code in this repository

### ISSUE THREAD

**Issue by Perevalov** [dbpedia/chatbot-ng#6]
This repo was updated last time during the GSoC 2021. So, some code is probably outdated. We need to understand is it really so and if yes, remove unnecessary parts from it.

This issue is related to: https://github.com/dbpedia/dbpedia-chatbot-backend/issues/7

# Definition of Done:

- [x] Create the corresponding `git tag` "gsoc2021" and release it on Github
- [x] Analyze the code, compare it to https://github.com/dbpedia/dbpedia-chatbot-backend, https://github.com/UditArora2000/GSoC2022_Question_Answering
- [x] Write your findings in this issue
- [x] Discuss with @Perevalov the future possibilities of removing/updating some parts of this repo

**Comment by Perevalov** [comment]
> @Perevalov just to be clear, we're comparing https://github.com/dbpedia/chatbot-ng to https://github.com/dbpedia/dbpedia-chatbot-backend, https://github.com/UditArora2000/GSoC2022_Question_Answering, correct?
> 
> "This repo was updated last time during the GSoC 2021. So, some code is probably outdated. We need to understand is it really so and if yes, remove unnecessary parts from it." Could you clarify if here, you're talking about https://github.com/dbpedia/chatbot-ng?

@muskan-k I mean whether the code in https://github.com/dbpedia/chatbot-ng is a subset of https://github.com/dbpedia/dbpedia-chatbot-backend or not. Or, for instance, whether a directory "RDF Visualizations" in  https://github.com/dbpedia/chatbot-ng is the same as https://github.com/dbpedia/dbpedia-chatbot-backend/tree/main/rdf_visualization. So, I personally not sure about the contents. The task is to understand whether the code in https://github.com/dbpedia/chatbot-ng still unique or duplicated in other repos. 

If it is outdated or duplicated in other repos, we need to update it. But keep in mind that https://github.com/dbpedia/chatbot-ng is for the frontend only.

**Comment by anbo-de** [comment]
FYI: Exemplary requests from Google Dialogflow are stored [here](https://github.com/dbpedia/dbpedia-chatbot-backend/tree/main/Webhook/requests). These files are used in Python tests stored [here](https://github.com/dbpedia/dbpedia-chatbot-backend/blob/main/Webhook/fulfillment/model_test.py).
We cannot be sure if this is still up-to-date.

**Comment by Perevalov** [comment]
@muskan-k Any progress or questions regarding this ticket?

**Comment by Perevalov** [comment]
@muskan-k Ok, I see. Now, knowing this, we need to clean up the `chatbot-ng` s.t. it only contains frontend parts. Let's discuss it tomorrow in detail

**Comment by Perevalov** [comment]
- [ ] Remove `RDF-Visualization` from `chatbot-ng`
- [ ] Create a new Google Dialogflow project and import the data from `chatbot-ng`

**Comment by muskan-k** [comment]
@Perevalov just wanted to recall what was discussed in the previous meeting - I need to import a only the Dialogflow-Agent directory from chatbot-ng and test it in a new project or remove the Webhook directory and test the resulting zip file? Could you please clarify.

**Comment by Perevalov** [comment]
@muskan-k please, use this URL for Dialogflow: https://demos.swe.htwk-leipzig.de/dbpedia-chatbot-webhook. This is a **reverse proxy** to the actual URL http://141.57.8.18:40194/webhook

**Comment by Perevalov** [comment]
> @Perevalov will this also work as reverse proxy for the other URL with port 40193?

No, if you need it for this, I can set it up. Let me know

**Comment by Perevalov** [comment]
> I'm seeing 502 bad gateway on loading the URL : https://demos.swe.htwk-leipzig.de/dbpedia-chatbot-webhook I've updated this URL in dialogflow fulfilment section. Am I going wrong somewhere? Also, the previous endpoint which was deployed and working now says cannot connect to server. Specifically, http://141.57.8.18:40194/health does not work but http://141.57.8.18:40193/visualize/urn:graph:24a1132b-6c7d-4770-8f30-e87cd43f8cf8 works fine.

Again, if you load it from browser, it won't work as it sends  HTTP GET request. The `/webhook` route is accepting HTTP POST requests https://github.com/dbpedia/dbpedia-chatbot-backend/blob/dd29ee14b33c23a571b9384d7d98dbb3b3380506/Webhook/main.py#L15

**Comment by Perevalov** [comment]
> @Perevalov 40193 is used for the RDF viz service. We've deployed both so I think we would need the reverse proxy for both right?
> 
> Also, https://demos.swe.htwk-leipzig.de/dbpedia-chatbot-webhook/health this is a GET request. This says 502 bad gateway too. I was also checking the previous URL, that fails to connect to the server. `/health` is GET request.

There is the following routing: https://demos.swe.htwk-leipzig.de/dbpedia-chatbot-webhook --> http://141.57.8.18:40194/webhook

Nothing else was added, so if you need HTTPS for `/health` and other endpoints, let me know, it doesn't happen automatically

**Comment by Perevalov** [comment]
@muskan-k Could you paste here all the infos on how you test it? I will try to debug and fix it

**Comment by muskan-k** [comment]
@Perevalov Tested the webhook call using POST request, works fine. No issues. 

![Image](https://github.com/dbpedia/chatbot-ng/assets/60001051/bb830efc-5dae-4184-aaeb-7d9cfe2b6a35)

**Comment by Perevalov** [comment]
> @Perevalov Tested the webhook call using POST request, works fine. No issues.
> 
> ![Image](https://user-images.githubusercontent.com/60001051/254279716-bb830efc-5dae-4184-aaeb-7d9cfe2b6a35.png)

Very good, that's very reliefing! I think we're done here.
